### ISSUE TITLE
replace check_exists_command with !system

### ISSUE THREAD

**Issue by wyattscarpenter** [kanliot/8mbwebm#1]
I'm trying to use this script on windows. If you replace the instances of check_exists_command with !system of a valid command, like converting `check_exists_command "ffmpeg"` to `!system('ffmpeg -version')`, that part should also work on windows. I would do this replacement myself except I don't know what a valid command for mediainfo is (`mediainfo --version`?) and I have no idea what bep is supposed to be!

**Comment by kanliot** [comment]
Yeah you're correctly reading the code. 

first check for OS type if you want to merge your code.  Just a suggestion, not saying you have to. 
`$OSNAME eq 'MSWin32'`

Then do something like this: https://stackoverflow.com/questions/28374996/how-to-check-if-command-is-exists

or you could just ignore the problem. 

If you just replace the function with a stub that always returns 1, I don't think anything bad will happen.  Certainly, the script won't behave properly if the depends are not installed. 

`bep` on my system plays a soft beep so that i know something happened. 

also, I've already gotten this script half working without MediaInfo.  ffprobe works just as well as mediainfo, so maybe make mediainfo optional is a new goal for me. 

Cheers.

**Comment by kanliot** [comment]
oh, and I'd love to have the script working on windows.  It's just that I haven't even bothered learning how to install perl on windows.   https://strawberryperl.com/releases.html I think?

**Comment by wyattscarpenter** [comment]
Yep, that's how I did it!

**Comment by wyattscarpenter** [comment]
Would it be acceptable to replace bep with `print "\a"` here? This prints a BEL character, thus making a one second noise: I have tested, and it works in cmd, powrshell, and bash on ubuntu on windows.

Of course, if bep provides a superior beep, it would trivial to write `!system("bep") or print "\a"` instead of completely replacing the bep command.

**Comment by kanliot** [comment]
TBH, I wasn't sure if you were still working on it. 

In my experience, people get really kind of BTFO when stuff starts beeping.  I will make the default behavior not to beep.  If you wanna add an new "command-line option" thats good.

I *Just* have to ask, is it working on windows?

**Comment by kanliot** [comment]
If you're still working on it, please make sure you finish, even if it's not perfectly consistent.  I want to make sure you have something to show when this is done.

**Comment by kanliot** [comment]
also you might need to replace this function with the new one.  this is off stackexchange, i think there's a module to do this but I can't find it.
```


sub quoteforshell { 
  return join ' ', map { 
    $^O eq 'MSWin32' ?
      '"' . s/"/""/gr . '"'
      : 
      "'" . s/'/'\\''/gr . "'" 
  } @_;
}
```

**Comment by wyattscarpenter** [comment]
I have gotten it to work on Windows! Not actually that difficult, just a matter of the `!system` thing and the `quoteforshell` thing. Unfortunately, while cleaning up the code I also broke it again, so I'll have to fix that. But, fairly soon (I am going at a leisurely pace) I should be able to make a commit to this repo that enables the script to run on Windows. It will also continue to run on unices, no separate branch required!

**Comment by wyattscarpenter** [comment]
I want to reassure you I have not abandoned this and will eventually complete it; I'm just busy with other concerns at the moment.

**Comment by kanliot** [comment]
very cool.  My advice is treat it like a bullshit homework assignment, and ask other people for answers and just cheat like hell.

**Comment by wyattscarpenter** [comment]
Finally got around to this today, thanks for your patience 😅
